// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpheMLvhBbrD17YUPxtnCCAK8LWoTpXMc',
    appId: '1:760966203382:web:98a61388f0db492bbbe9d7',
    messagingSenderId: '760966203382',
    projectId: 'givision',
    authDomain: 'givision.firebaseapp.com',
    storageBucket: 'givision.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCUfsTSfcetMl6YGt8qUvsRVK1MxcnpM4',
    appId: '1:760966203382:android:873818b4f47ea9e6bbe9d7',
    messagingSenderId: '760966203382',
    projectId: 'givision',
    storageBucket: 'givision.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwPj7CHQfOZSyxgGndLMkHKksdiwzWRyo',
    appId: '1:760966203382:ios:bfa114ebc8ac8166bbe9d7',
    messagingSenderId: '760966203382',
    projectId: 'givision',
    storageBucket: 'givision.appspot.com',
    iosClientId: '760966203382-sqtpuktd10n80c7k3pnop96n6eb12qg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.givison',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwPj7CHQfOZSyxgGndLMkHKksdiwzWRyo',
    appId: '1:760966203382:ios:49f84118a0491bbebbe9d7',
    messagingSenderId: '760966203382',
    projectId: 'givision',
    storageBucket: 'givision.appspot.com',
    iosClientId: '760966203382-h92b3to9107p54pdle4dnf7ls9ecn7js.apps.googleusercontent.com',
    iosBundleId: 'com.example.givison.RunnerTests',
  );
}
